use_frameworks!

target 'firebase_Example' do
  pod 'firebase', :path => '../'

  target 'firebase_Tests' do
    inherit! :search_paths

    
  end

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
end
